const db = [
  {
    id: 1,
    logo: "tiktok.png",
    company: "Tiktok",
    star: "3.6",
    title: "Backend Software Engineer",
    category: "Backend",
    posted: "1 minutes ago",
    location: "Singapore",
    salary: "S$9,492 - S$18,996 / mth",
    requirements: ["Java", "Python"],
  },
  {
    id: 2,
    logo: "gxs.png",
    company: "GXS Bank",
    star: "4.2",
    title: "Frontend Software Engineer",
    category: "Frontend",
    posted: "1 minutes ago",
    location: "Singapore",
    salary: "S$9,492 - S$18,996 / mth",
    requirements: ["Java", "Python", "Javascript"],
  },
  {
    id: 3,
    logo: "dyson.png",
    company: "Dyson",
    star: "4.5",
    title: "Enbedded Software Test Engineer",
    category: "QA",
    posted: "1 minutes ago",
    location: "Singapore",
    salary: "S$9,492 - S$18,996 / mth",
    requirements: ["Java", "Python", "CI"],
  },
  {
    id: 4,
    logo: "govtech.png",
    company: "Govtech",
    star: "4.1",
    title: "Cybersecurity Engineer",
    category: "Cybersec Eng",
    posted: "1 minutes ago",
    location: "Singapore",
    salary: "S$9,492 - S$18,996 / mth",
    requirements: ["Java"],
  },
  {
    id: 5,
    logo: "dbs.png",
    company: "DBS Bank",
    star: "3.3",
    title: "Full Stack Developer",
    category: "Fullstack",
    posted: "1 minutes ago",
    location: "Singapore",
    salary: "S$9,492 - S$18,996 / mth",
    requirements: ["Java", "Python", "React"],
  },
  {
    id: 6,
    logo: "airwallex.png",
    company: "Airwallex",
    star: "3.6",
    title: "Senior Software Engineer",
    category: "Fullstack",
    posted: "1 minutes ago",
    location: "Singapore",
    salary: "S$9,492 - S$18,996 / mth",
    requirements: ["AWS", "Docker"],
  },
];

export default db;
